language: php
php:
  - 8.0

install:
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-9.phar
  - wget -O coveralls.phar https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar

script:
  - mkdir -p build/logs
  - php phpunit.phar --bootstrap test/autoload.php test -c phpunit.xml

after_success:
  - travis_retry php coveralls.phar

sudo: false
