language: php
php:
  - 8.0

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-9.phar

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage php phpunit.phar --bootstrap test/autoload.php test -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

sudo: false
