language: php
php:
  - 7.0
  - 7.1

install:
  - wget https://phar.phpunit.de/phpunit-6.2.3.phar
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar

script:
  - mkdir -p build/logs
  - php phpunit-6.2.3.phar --bootstrap tests/autoload.php tests -c phpunit.xml

after_success:
  - travis_retry php coveralls.phar

sudo: false
